# Generated by Django 6.0 on 2026-01-06 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('excerpt', models.TextField(max_length=300, verbose_name='خلاصه مقاله')),
                ('content', models.TextField(verbose_name='محتوای مقاله')),
                ('category', models.CharField(choices=[('tech', '🖥️ تکنولوژی و کالای دیجیتال'), ('game', '🎮 بازی و سرگرمی'), ('edu', '📚 آموزش')], default='tech', max_length=10, verbose_name='دسته\u200cبندی')),
                ('image', models.ImageField(blank=True, help_text='تصویر اصلی مقاله', null=True, upload_to='articles/%Y/%m/%d/', verbose_name='تصویر مقاله')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'), models.Index(fields=['category'], name='blog_articl_categor_6a5607_idx'), models.Index(fields=['published_at'], name='blog_articl_publish_cc3c64_idx')],
            },
        ),
    ]
